[package]
name = "watcher"
version = "0.1.0"
authors = ["J/A <archer884@gmail.com>"]

[dependencies]
fortune-cookie = { git = "https://github.com/archer884/fortune-cookie.git" }
hiirc = "*"
icndb = { git = "https://github.com/archer884/icndb.git" }
rsilio = { git = "https://github.com/archer884/rsilio.git" }
rustc-serialize = "*"
time = "*"
toml = "*"
