[package]
name = "watcher"
version = "0.1.0"
authors = ["J/A <archer884@gmail.com>"]

[dependencies]
hiirc = "*"
icndb = { git = "https://github.com/archer884/icndb.git" }
rsilio = { git = "https://github.com/archer884/rsilio.git" }
time = "*"
toml = "*"
